# Generated by Django 5.1.2 on 2024-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(),
        ),
    ]
